### ISSUE TITLE
First name and professional name are readonly

### ISSUE THREAD

**Issue by T-Brick** [diderot-edu/diderot-feedback#114]
The first name and professional name fields cannot be updated, meaning that students (and potentially instructors) who have had their name changed or who do not use a particular name will be forced to see said old name.

**Comment by dialmond** [comment]
I also have a problem with this, haha, can we bump this issue? Umut Acar reacted with a thumbs up but it's been a year...

**Comment by T-Brick** [comment]
bump

**Comment by umutacar** [comment]
you can edit your "preferred name" now under your profile

**Comment by dialmond** [comment]
Hi Umut,

I have some issues with this solution, still. First of all, the preferred name isn't used in the drop-down menu when a student clicks on their profile.

But more importantly, why does Diderot need to have static first name / professional name fields in the first place? If I created an account today I could choose what name to enter in these fields. It's not necessarily my legal name, it's not pulled from CMU's records, the name on my account is the name that I *chose* to enter at registration. If I can choose the name associated with my account at registration, why can't I choose to change it now?

A preferred name field makes more sense for something like CMU's SIO, where legal names are needed for legal purposes, and preferred names are (ideally) used for everything else. But it really doesn't look like Diderot needs to keep track of a student's legal name or name history.

The student rosters that CMU gives to my professors has my preferred name on it. If the first name field is shown to my instructors then there's going to be an in-congruence there.

As a creator of software for a university you're going to have a lot of users, users who *have to* use your software for their courses. You're going to have future users, current users like me, who will need to change their names. This shouldn't need to be done manually every time, requiring a user to go through the process of contacting you and waiting for you to change it. Users should have the same autonomy over their names that Diderot gives at registration at all times.

I hope you can clarify why Diderot needs to keep track of the name entered at registration. Please consider re-opening this issue, too, especially when the preferred name isn't even used everywhere.

And while I'm making this issue, could you please change the name that appears in the first name field to my preferred name? 

Thanks,
Cassidy

**Comment by umutacar** [comment]
Hi Cassidy, thank you for your thoughts.  
The name not showing under the avatar is an oversight on our side.  It will be fixed soon.

We do need to be consistent with SIO.  We can also allow course staff edit the first and last names so the names can be changed with their knowledge.

**Comment by umutacar** [comment]
ohh my, this is getting interesting. Thea, this is not a university funded or supported project.  i am developing and offering diderot to users using external research funds.  (i even use my own personal money for some expenses) .   there are limits to my time and our funding and what i can do.  i think your anger is right and your heart is at the right place but it is directed towards the wrong person.

**Comment by umutacar** [comment]
Also, to be clear, i have not fixed this because of complaints from DEI or Title X.  I go through our list of issues based the availability of funding and time.

**Comment by dialmond** [comment]
> Hi Cassidy, thank you for your thoughts. The name not showing under the avatar is an oversight on our side. It will be fixed soon.
> 
> We do need to be consistent with SIO. We can also allow course staff edit the first and last names so the names can be changed with their knowledge.


Hi Umut,

I'm still not sure this is a consistent solution.  I have multiple instructors on Diderot. If it just takes one to change my name, won't the other instructors not be aware of the change?

But again, more importantly, as mentioned none of CMU's other platforms require students to *request* a name change. I feel like I shouldn't have to rely on the benevolence of my professors to not get deadnamed by your software. I shouldn't have to expose my deadname, my old name, to my professors in order to change it. When I changed my preferred name with CMU's SIO, *none of my professors were notified*. To my knowledge none of my current professors could have a chance to know my deadname *except* through Diderot.

If I'm required to use your software for my courses at CMU, I feel like it should respect CMU's [student privacy rights](https://www.cmu.edu/policies/student-and-student-life/privacy-rights-students.html) and CMU's [preferred name policy](https://www.cmu.edu/hub/registrar/docs/preferred-name.pdf). CMU gives me the privacy rights to avoid showing my professors my old name via directory information, and the ability to easily update my name in all places where it does not need to be used for legal business. Shouldn't Diderot be consistent with this?

I understand that this isn't a university funded or supported project, but clearly Diderot is integral to many classes operations. It was developed by CMU professors for use at CMU. I think it should therefore reflect official CMU policies.

I think notifying professors of a name change is a valid concern but in my case, from my professors' perspectives I'm *not* changing my name, this is the name I've always used with them. 

Finally, if I'm correct hasn't Diderot received school funding in the past? From [this Tartan article](https://thetartan.org/2020/2/24/scitech/diderot):
> We have support, especially financial support, from the Dean’s office, and that is one of the reasons we are able to expand within CMU right now. That support allows us to grow here," Ada said.

Fundamentally, the source of Diderot's funding isn't important. What is important, however, is the inconsistencies between Diderot and CMU's official policies, especially given the widespread use of the program within university courses.

Thanks,
Cassidy

**Comment by T-Brick** [comment]
If I shouldn't be mad at you then who should I be mad at?

**Comment by umutacar** [comment]
Hi Thea @T-Brick 
Let me start by saying that I understand your anger, and in fact, I share it.   Suffices to say that I made the case that Diderot ought to be funded adequately given the many students and courses using it (any many others that want to use but I am unable to support).  But the folks controlling the funding do not agree... But that is just me trying.  We should remember that there are limits to what I can do---I am just a professor with a strange name! 

I think you will have better luck.  So...  Instead of telling you who you can get angry at, I want to recommend a more constructive step and  recommend writing to  President  Farnam Jahanian.  The buck would have to stop with him.
https://www.cs.cmu.edu/~farnam/

Here is some data regarding Diderot usage since Spring 2019

-- Number of course registrations 13,557
-- Number of unique users: 7732 (on average a student takes ~2 courses on Diderot)
-- Number of courses: over 100
-- Number of API requests served on a typical semester day: over 1 Million

**Comment by umutacar** [comment]
Hi Cassidy @dialmond 
I added the `Preferred Name` option because it is compatible with SIO and similar systems.  

It might be possible to support editing names but I need to think through it carefully, because there are a relatively large number of features on Diderot (some you might not be aware of because the course you are taking is not using them, and because you are student, and you see a limited interface).  In this context, I went with the Preferred name solution because I realized it is important and I wanted to get it done asap.

For example, things that come to mind...
1) Most faculty upload SIO rosters on Diderot instead of allowing students self register.  In this case, it might be confusing to allow students to change names themselves
2) I need to check if this would this work with SIO (we do send data back to SIO so need to check that different names does not trip it up) 
3) I need to check with the instructors and take into account their feedback. Instructors can download various pieces of information from Diderot and use it to do various analysis, also based on SIO data.

**Comment by T-Brick** [comment]
I'll make sure to write to Farnam about Diderot's funding, since the university not paying for its frankly unacceptable.

> Most faculty upload SIO rosters on Diderot instead of allowing students self register. In this case, it might be confusing to allow students to change names themselves

1. SIO should not be giving legal/incorrect names to professors in the first place. This means if I take a course my name would not match the one on the roster.
2. Mutliple students can have the same name, using exclusively names as identifiers is not sound and I'm certain that SIO and other university resources account for this.
3. Canvas, piazza, gradescope (services similar to Diderot) don't send incorrect names to professors. In fact professors seemed very well positioned to deal with this already, since many international students use an "American" name on these resource which often differs from the name on SIO (or vice-versa)

And even if SIO does give incorrect names to instructors, that does not justify Diderot harming it own users (students) by doing the same.

**Comment by umutacar** [comment]
An update on this issue
Cassidy @dialmond did amazing work and figured out the CMU SIO policies.  We then met in person and talked.  Based on this conversation, I have made some updates to Diderot's handling of names and made the first and last name editable.  I hope that the updates have resolved this issue to satisfaction.  

For all of those that are negatively impacted by this, I am deeply sorry that it has taken this so long to fix.
