### ISSUE TITLE
Deleting/Hiding posts on Web UI

### ISSUE THREAD

**Issue by gauravmm** [diderot-edu/diderot-feedback#5]
Allow us to delete/hide posts on the web UI.

**Comment by ada-anil** [comment]
Posts can be deleted. You have to click on the 'Edit' option to see the delete button. Let me know if that resolves the issue.

**Comment by gauravmm** [comment]
I don't see the delete button; is this restricted to instructors?

**Comment by ada-anil** [comment]
The top level posts can be deleted by TAs. The comments/replies to posts can only be deleted by instructors (you can instead edit the comment and delete the text).

I will revisit the overall delete policy.

**Comment by gauravmm** [comment]
I think being able to edit is constructively the ability to delete; I'd appreciate being able to delete to unclutter.

**Comment by ada-anil** [comment]
Not quite because if you delete a post, you are also deleting the comments attached to it as well (which you may not own). So that is a consideration I would like to keep in mind.

**Comment by gauravmm** [comment]
Can you support hiding them?

**Comment by umutacar** [comment]
The new diderot post office is now more "issue/ticket" driven.  Posts are more like issues/tickets and can be opened and closed and easily filtered by these properties.  This has many advantages over deletion, because when you delete a post, you are usually (as a course staff) deleting a student's work.  One could argue that this is not fair and ought not be supported.  We still do support it but you have to go a bit out of your way to do it.
