### ISSUE TITLE
Cannot view student solutions when they have attachments

### ISSUE THREAD

**Issue by khale** [diderot-edu/diderot-feedback#88]
Several students are complaining that the images look small when they attach them. I can't see a way to zoom in on them, and when I go to view their solutions to verify,  (books -> chapter (submittable) -> manage submissions  -> (select student) -> view answers (on any question), the answer page fails to load completely. Tried on both firefox and chrome.

**Comment by umutacar** [comment]
Image size is propotional to solution box. Make it larger ny padding your solution with tildes.

Send me a link to the broken submission Please?

**Comment by khale** [comment]
Ah I see. 
here is the link to the submission in question
https://www.diderot.one/courses/79/books/326/chapter/4338/submissions/5488/answers

**Comment by umutacar** [comment]
"View Answers" is a currently being developed and is intended for creating a rubric for that question, which can then be used to grade the question.  this is still being developed so it might not work properly.

On this submission, there is still a problem: the student's answer are not shown even though the history shows that they have entered their answer.  

Will look into this. but one important piece of caution:
the submission system is not robust under simultaneous accesses from multiple devices / browsers.  if the student accesses the same quiz from a different device, because it is a different device, the system will not notice the concurrency and could allow multiple writers to (auto)save at the same time.  

Students should use one browser (on one devices) when taking quizzes.  Basically concurrency management is being done in the front-end and this has some limitations.

We will fix this soon but this is so  now.

**Comment by umutacar** [comment]
should be fixed now.
