### ISSUE TITLE
Theorem popups do not close

### ISSUE THREAD

**Issue by mivkov** [diderot-edu/diderot-feedback#99]
Is there any way to close the Theorem popups after hovering over a link? They persist even after scrolling.
![image](https://user-images.githubusercontent.com/19914400/111367450-21b40280-866b-11eb-9855-2d586113acca.png)
![image](https://user-images.githubusercontent.com/19914400/111367628-4d36ed00-866b-11eb-9008-c5763170f6df.png)

**Comment by umutacar** [comment]
Moving the mouse pointer away from the link should do it.

**Comment by mivkov** [comment]
These screenshots were taken after moving my mouse away (unfortunately I can't take good photos on PC without snipping tool).
What I hypothesize is happening is the following: 
1. I hover over the link
2. The link starts to load (the top of the page shows the orange bar crossing the screen)
3. If I remove my mouse before the link loads, then the popup no longer tracks my mouse movement and exists as its own entity forever. If I do wait for the popup to load, then it has no issues closing.

**Comment by umutacar** [comment]
yes, i think you "theorem" is correct ;)

we can do a few things
1) wait for a second before we start loading (or preload) so that
accidental moves over the link does not pop up the shortcut window. [note
to self: here is an algorithm to do this: 1) load the data, wait for it to
arrive, check that the mouse is still within the hot zone, and then display]
2) include at "X" to allow manual close

-- Umut

**Comment by umutacar** [comment]
should be fixed
